#!/usr/bin/env bats

setup() {
    load "${BATS_TEST_DIRNAME}/test_helper"
}

# -------------------- check_configs_sync.sh --------------------
# The vendored-config drift guard: diffs .github/upstream-baseline/{config.yaml,
# global_settings.yaml} against upstream realsense-ros at the pinned tag. The
# network diff is not run here; we assert the --help contract plus the pure
# CMakeLists parser (extract_global_default) that reconstructs upstream's
# build-time global_settings default. main is guarded to direct execution, so
# sourcing the script only defines the helpers.

@test "check_configs_sync.sh -h exits 0" {
    run bash /lint/check_configs_sync.sh -h
    assert_success
}

@test "check_configs_sync.sh --help exits 0" {
    run bash /lint/check_configs_sync.sh --help
    assert_success
}

@test "check_configs_sync.sh -h prints usage" {
    run bash /lint/check_configs_sync.sh -h
    assert_line --partial "Usage:"
}

@test "check_configs_sync.sh is executable" {
    [ -x /lint/check_configs_sync.sh ]
}

@test "extract_global_default reads the OFF (else) branch default from CMakeLists" {
    # global_settings.yaml is generated by realsense2_camera/CMakeLists.txt from
    # the USE_LIFECYCLE_NODE option; the else (default OFF) branch writes
    # "use_lifecycle_node: false". The parser must return exactly that, ignoring
    # the if (ON) branch's "true".
    run bash -c '
        f="$(mktemp)"
        cat > "$f" <<"CMAKE"
if(USE_LIFECYCLE_NODE)
  file(WRITE OUT "use_lifecycle_node: true\n")
else()
  file(WRITE OUT "use_lifecycle_node: false\n")
endif()
CMAKE
        source /lint/check_configs_sync.sh
        extract_global_default "$f"
        rm -f "$f"'
    assert_success
    assert_output "use_lifecycle_node: false"
}

@test "extract_global_default returns nothing when the block is absent (drift path)" {
    # A CMakeLists without the USE_LIFECYCLE_NODE block yields no default, which
    # main treats as drift (cannot reconstruct the expected global_settings).
    run bash -c '
        f="$(mktemp)"
        cat > "$f" <<"CMAKE"
project(realsense2_camera)
add_library(foo bar.cpp)
CMAKE
        source /lint/check_configs_sync.sh
        extract_global_default "$f"
        rm -f "$f"'
    assert_success
    assert_output ""
}
