#!/usr/bin/env bash
#
# Check the vendored RealSense example configs against upstream at the pinned
# realsense-ros tag.
#
# config/realsense/config.yaml and config/realsense/global_settings.yaml are
# vendored verbatim from IntelRealSense/realsense-ros at the tag in the
# Dockerfile ARG REALSENSE_ROS_VERSION. This script parses that tag, fetches the
# upstream sources at that tag, and diffs them against the committed copies.
# Exit 0 when both are identical; non-zero (printing the unified diffs) on drift.
# Used locally and by .github/workflows/upstream-bump.yaml. Mirrors
# script/check_udev_rules_sync.sh (which watches the udev rules against the
# librealsense SDK tag).
#
# global_settings.yaml is not a tracked source file upstream: it is generated by
# realsense2_camera/CMakeLists.txt from the USE_LIFECYCLE_NODE option (default
# OFF -> "use_lifecycle_node: false"). We therefore reconstruct its expected
# content from the CMakeLists default (else) branch rather than fetching a raw
# file.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_DIR
readonly REPO_ROOT="${SCRIPT_DIR}/.."
readonly DOCKERFILE="${REPO_ROOT}/Dockerfile"
readonly CONFIG_LOCAL="${REPO_ROOT}/config/realsense/config.yaml"
readonly GLOBAL_LOCAL="${REPO_ROOT}/config/realsense/global_settings.yaml"
readonly CONFIG_UPSTREAM_PATH="realsense2_camera/examples/launch_params_from_file/config/config.yaml"
readonly CMAKE_UPSTREAM_PATH="realsense2_camera/CMakeLists.txt"

usage() {
  cat >&2 <<'EOF'
Usage: check_configs_sync.sh [-h|--help]

Diff the vendored config/realsense/config.yaml and
config/realsense/global_settings.yaml against the upstream
IntelRealSense/realsense-ros sources at the tag pinned in the Dockerfile ARG
REALSENSE_ROS_VERSION.

Exits 0 when both vendored copies match upstream, non-zero (printing the unified
diffs) when they have drifted. Run it locally or from the scheduled
upstream-bump workflow to catch a stale config vendor.

Options:
  -h, --help   Show this help and exit.
EOF
}

# Fetch a raw file from realsense-ros at the pinned tag into the named temp file.
fetch_upstream() {
  local tag="${1}"
  local path="${2}"
  local dest="${3}"
  local url="https://raw.githubusercontent.com/IntelRealSense/realsense-ros/${tag}/${path}"
  if ! curl -fsSL "${url}" -o "${dest}"; then
    echo "check_configs_sync.sh: failed to fetch ${url}" >&2
    return 1
  fi
}

main() {
  case "${1:-}" in
    -h | --help)
      usage
      return 0
      ;;
    "") ;;
    *)
      echo "check_configs_sync.sh: unknown argument '${1}'" >&2
      usage
      return 1
      ;;
  esac

  local f
  for f in "${CONFIG_LOCAL}" "${GLOBAL_LOCAL}"; do
    if [[ ! -f "${f}" ]]; then
      echo "check_configs_sync.sh: vendored config not found: ${f}" >&2
      return 1
    fi
  done

  local pinned_tag
  pinned_tag="$(grep -oP 'ARG REALSENSE_ROS_VERSION="\K[^"]+' "${DOCKERFILE}" || true)"
  if [[ -z "${pinned_tag}" ]]; then
    echo "check_configs_sync.sh: could not parse REALSENSE_ROS_VERSION from ${DOCKERFILE}" >&2
    return 1
  fi

  local upstream_config upstream_cmake expected_global
  upstream_config="$(mktemp)"
  upstream_cmake="$(mktemp)"
  expected_global="$(mktemp)"
  # shellcheck disable=SC2064
  trap "rm -f '${upstream_config}' '${upstream_cmake}' '${expected_global}'" EXIT

  local drift=0

  # config.yaml: vendored verbatim from a tracked upstream file.
  fetch_upstream "${pinned_tag}" "${CONFIG_UPSTREAM_PATH}" "${upstream_config}"
  if diff -u "${upstream_config}" "${CONFIG_LOCAL}" \
      --label "upstream@${pinned_tag}:config.yaml" --label "vendored:config.yaml"; then
    echo "check_configs_sync.sh: config.yaml in sync with realsense-ros ${pinned_tag}"
  else
    echo "check_configs_sync.sh: DRIFT -- config.yaml differs from realsense-ros ${pinned_tag}" >&2
    drift=1
  fi

  # global_settings.yaml: reconstruct upstream's build-time default from the
  # CMakeLists else (USE_LIFECYCLE_NODE=OFF) branch's file(WRITE ...) literal.
  fetch_upstream "${pinned_tag}" "${CMAKE_UPSTREAM_PATH}" "${upstream_cmake}"
  # Scope to the USE_LIFECYCLE_NODE if/else block, take the else (default OFF)
  # branch's file(WRITE ...) string literal. Portable awk (no gawk-only 3-arg
  # match / capture array) so it runs under ubuntu-latest's mawk in CI.
  local default_line
  default_line="$(awk '
    /if\(USE_LIFECYCLE_NODE\)/ { in_block = 1 }
    in_block && /else\(\)/ { seen_else = 1 }
    in_block && seen_else && /use_lifecycle_node:/ {
      line = $0
      sub(/^[^"]*"/, "", line)
      sub(/\\n".*$/, "", line)
      print line
      exit
    }
    in_block && /endif\(\)/ { in_block = 0 }
  ' "${upstream_cmake}")"
  if [[ -z "${default_line}" ]]; then
    echo "check_configs_sync.sh: could not parse global_settings default from ${CMAKE_UPSTREAM_PATH}" >&2
    drift=1
  else
    printf '%s\n' "${default_line}" > "${expected_global}"
    if diff -u "${expected_global}" "${GLOBAL_LOCAL}" \
        --label "upstream@${pinned_tag}:global_settings.yaml" \
        --label "vendored:global_settings.yaml"; then
      echo "check_configs_sync.sh: global_settings.yaml in sync with realsense-ros ${pinned_tag}"
    else
      echo "check_configs_sync.sh: DRIFT -- global_settings.yaml differs from realsense-ros ${pinned_tag}" >&2
      drift=1
    fi
  fi

  return "${drift}"
}

main "${@}"
